

on:
  pull_request:
    branches:
      - master

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.12
      - name: Run Go Tests 
        run: |
          make deps
          make check